name: jafjaf
description: ''
version: 0.0.1-SNAPSHOT
author: kishore@simpledatalabs.com
language: sql
buildSystem: sql
pipelines:
  pipelines/demo:
    name: demo
    description: ''
    author: mei@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-17 00:49:09'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline:
  name: sqlPipeline
  description: kishore@simpledatalabs.com
  author: kishore@simpledatalabs.com
  createdAt: '2022-12-09 05:43:56'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
